id = "sushi-theme"
name = "SUSHI"
description = "A fresh theme inspired by Sushi."
version = "0.0.1"
schema_version = 1
authors = ["tomopumipumi <tomo.pumi.pumi@gmail.com>"]
repository = "https://github.com/tomopumipumi/sushi-theme"
